# Introduction to NumPy
NumPy (Numerical Python) is a powerful library for numerical computing in Python. It provides support for arrays and matrices, along with a large collection of mathematical functions.

In [2]:
import numpy as np

# Diffferent Between List and numpy:
List: Slower for numerical operations due to the dynamic typing of elements and lack of optimization for numerical computations.

NumPy Array: Faster for numerical operations as it uses fixed data types and optimized C/C++ libraries for performance.

In [85]:
import time
from time import time 

In [86]:
x = time()
y = [i for i in range(10000000)]
z = time()
print(x-z)

-1.332486629486084


In [87]:
x = time()
y =  np.arange(10000000)
z = time()
print(x-z)

-0.24564290046691895


# Creating Arrays
Arrays are the central data structure in NumPy. You can create arrays using various functions.

In [89]:
x = np.array([1,2,3,4])   # 1D arrary
y = np.arange(0,5)
print(x, y ,type(x) ,type(y),x.ndim, y.ndim, sep='\n\n')

[1 2 3 4]

[0 1 2 3 4]

<class 'numpy.ndarray'>

<class 'numpy.ndarray'>

1

1


In [70]:
x = np.array([[1,2,3],  
             [4,5,6]])   # 2D arrary
y = np.arange(9).reshape(3,3)
print(x, y ,type(x),type(y), x.ndim, y.ndim ,sep='\n\n')

[[1 2 3]
 [4 5 6]]

[[0 1 2]
 [3 4 5]
 [6 7 8]]

<class 'numpy.ndarray'>

<class 'numpy.ndarray'>

2

2


In [73]:
x = np.array([[[1,2,3],  
             [4,5,6]],
             [[7,8,9],
             [10,11,12]]])   # 3D arrary
y = np.arange(18).reshape(2,3,3)
print(x, y ,type(x),type(y), x.ndim, y.ndim ,sep='\n\n')

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]

<class 'numpy.ndarray'>

<class 'numpy.ndarray'>

3

3


# Array Attributes:

In [146]:
x = np.arange(12).reshape(4,3)
print(x)
print("Shape:", x.shape)
print("Data type:", x.dtype)
print("Size:", x.size)
print("Number of dimensions:", x.ndim)
print("size of elments(in bytes) is itemssize :", x.itemsize)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Shape: (4, 3)
Data type: int32
Size: 12
Number of dimensions: 2
size of elments(in bytes) is itemssize : 4


# Using zeros and ones:
* zeros:

   zeros is a function in NumPy that creates an array filled with zeros. You can specify the shape of the array by passing a tuple of dimensions as an argument.
* ones : 

    np.ones creates an array filled with ones. You can specify the shape of the array, such as 1D, 2D, etc.


In [109]:
x = np.zeros((3,3))
y = np.ones((3,3))
print(x,y, sep='\n\n') 

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


# linspace
The numpy.linspace function generates evenly spaced numbers between a specified start and end value. You can choose how many numbers you want in that range.


In [7]:
np.linspace(0,10,30)  # the range 0 to 10 that is equal patrs to 30 

array([ 0.        ,  0.34482759,  0.68965517,  1.03448276,  1.37931034,
        1.72413793,  2.06896552,  2.4137931 ,  2.75862069,  3.10344828,
        3.44827586,  3.79310345,  4.13793103,  4.48275862,  4.82758621,
        5.17241379,  5.51724138,  5.86206897,  6.20689655,  6.55172414,
        6.89655172,  7.24137931,  7.5862069 ,  7.93103448,  8.27586207,
        8.62068966,  8.96551724,  9.31034483,  9.65517241, 10.        ])

# identity
The numpy.identity function creates a square matrix with ones on the main diagonal and zeros elsewhere. It’s useful for creating the identity matrix, which acts as a neutral element in matrix multiplication.

In [8]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [11]:
np.eye(5) # identity

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# np.random.rand
np.random.rand generates random numbers from a uniform distribution between 0 and 1.

In [128]:
np.random.rand(3,3)


array([[0.18281374, 0.36821445, 0.0603158 ],
       [0.60364102, 0.21273558, 0.28665062],
       [0.87741599, 0.53151811, 0.69625793]])

# np.random.randint
The np.random.randint function generates random integers between a specified low and high value.

In [130]:
np.random.randint(0, 10,(3,3))

array([[7, 2, 6],
       [9, 9, 7],
       [2, 5, 8]])

# np.random.randn
The numpy.random.randn function generates an array of random numbers from a standard normal distribution (mean 0, variance 1).

In [125]:
print(np.random.randn(3, 3))

[[-0.54592653  0.44174691 -0.16855845]
 [-0.37043551  0.82195904 -1.76749988]
 [-0.81491078  1.34354001  0.78705635]]


# np.random.choice
np.random.choice selects random elements from an array or range, with options for choosing with or without replacement.

In [5]:
np.random.choice(10,(3,3))

array([[8, 7, 9],
       [8, 1, 1],
       [7, 3, 7]])

# np.random.seed()
np.random.seed() sets the random seed for NumPy's random number generator, ensuring reproducibility of random results in simulations and experiments.

In [212]:
np.random.seed(9)
np.random.rand(3,3)

array([[0.01037415, 0.50187459, 0.49577329],
       [0.13382953, 0.14211109, 0.21855868],
       [0.41850818, 0.24810117, 0.08405965]])

# np.floor
np.floor rounds each number in an array down to the nearest integer

In [132]:
np.floor(6.6)

6.0

# np.ceil :
np.ceil rounds each number in an array up to the nearest integer.

In [133]:
np.ceil(6.4)

7.0

# np.round
np.round rounds the elements of an array to a specified number of decimal places.

In [135]:
np.round(6.6)

7.0

In [10]:
np.round(6.4)

6.0

# changing data type :
Changing data type means converting the values in an array from one type (like integer) to another type (like float).




In [158]:
x = np.arange(18).reshape(2,3,3) 
print(x,x.dtype)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]] int32


In [157]:
x.astype('float32')

array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.]],

       [[ 9., 10., 11.],
        [12., 13., 14.],
        [15., 16., 17.]]], dtype=float32)

# Array Operation
Array Operations data type: It refers to the type of mathematical operations (like addition or multiplication) that can be performed on arrays and how they affect the data in those array

In [159]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print(x + y)   # Element-wise addition
print(x * y)   # Element-wise multiplication

[5 7 9]
[ 4 10 18]


# np.dot
The np.dot function performs matrix multiplication or computes the dot product of two arrays. to work the dot product the frist matrix  colum size and second matrix row size should same  
ex:
(4--r,3--c) and (3--r,4--c)


In [184]:
x = np.arange(12).reshape(4,3) 
y = np.arange(12,24).reshape(3,4)
x.dot(y)

array([[ 56,  59,  62,  65],
       [200, 212, 224, 236],
       [344, 365, 386, 407],
       [488, 518, 548, 578]])

In [187]:
x = np.arange(12).reshape(4,3)
y = np.arange(12,24).reshape(4,3)
x.dot(y)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

# Universal Functions (ufuncs):
    Universal Functions (ufuncs) in NumPy are built-in functions that perform element-wise operations on arrays, like addition, subtraction, or square roots, efficiently.

In [168]:
x = np.array([1, 2, 3, 4])

print(np.sqrt(x))    # Square root
print(np.exp(x))     # Exponential
print(np.sin(x))     # Sine

[1.         1.41421356 1.73205081 2.        ]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


# Statistics
Statistics involves collecting, analyzing, and interpreting numerical data to make decisions or draw conclusions about a population or phenomenon.




In [17]:
a = np.array([1, 2, 3, 4, 5])

print(np.mean(a))   # Mean
print(np.median(a)) # Median
print(np.std(a))    # Standard deviation
print(np.var(a))    # Variance
print(np.min(a))    # minimum value 
print(np.max(a))    # maximum value
print(np.sum(a))    # sum of the all values
print(np.prod(a))   # multiply all the values (1*2*3*4*5)
print(np.argmax(a)) # index position  of maxmimum value
print(np.argmin(a)) # index position  of minimum value

3.0
3.0
1.4142135623730951
2.0
1
5
15
120
4
0


# Transposing:
    Flipping a matrix over its diagonal so rows become columns and columns become rows.

In [191]:
x = np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [192]:
x.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

# ravel
In NumPy, the n NumPy, the ravel() function is used to flatten an array, meaning it collapses the array into a 1D array. () function is used to flatten an array, meaning it collapses the array into a 1D array. 

In [145]:
x = np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [146]:
np.ravel(x) # its convert to 1D array

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

# Indexing:
     Access specific elements of an array using their position.
    

# 1d array :

In [10]:
x = np.arange(0,5) # indexing on 1d array
x

array([0, 1, 2, 3, 4])

In [12]:
x[2]  # ccessing 2 from the array by using positive index

2

In [30]:
x[-3] # ccessing 2 from the array by using negative index 

2

# 2d array :

In [27]:
y = np.random.randint(0,12,(3,3)) # indexing on 2d array
y

array([[11,  9,  0],
       [ 7,  2, 10],
       [ 1,  9, 11]])

In [28]:
y[1,1]  # ccessing 2 from the matrix by using positive index

2

In [34]:
y[-2,-2] # ccessing 2 from the matrix by using negative index 

2

# 3d array :

In [46]:
z = np.random.randint(0,100,(2,3,3)) # indexing on 3d array
z

array([[[ 4, 43, 95],
        [29, 39, 35],
        [74, 11, 57]],

       [[95, 28, 26],
        [26, 56, 36],
        [17, 66, 33]]])

In [47]:
z[1,1,1]  # ccessing 56 from the matrix by using positive index 

56

In [48]:
z[-1,-2,-2] # ccessing 2 from the matrix by using negative index 

56

# 4d array :

In [61]:
z = np.random.randint(0,100,(2,2,3,3)) # indexing on 4d array
z

array([[[[ 2, 55, 16],
         [55, 54, 42],
         [12, 56,  2]],

        [[80, 74, 22],
         [24,  9, 84],
         [69, 43, 16]]],


       [[[76, 70, 53],
         [54,  8, 32],
         [52, 57, 38]],

        [[16,  7, 60],
         [66,  5, 33],
         [59, 50, 10]]]])

In [62]:
z[1,1,1,2]  # ccessing 33 from the matrix by using positive index 

33

In [64]:
z[-1,-1,-2,-1] # ccessing 33 from the matrix by using negative index  

33

# Slicing [start : end : step] :
    Extract a subset of elements from an array.

# 1d array :

In [66]:
x = np.arange(0,5) # Slicing on 1d array
x

array([0, 1, 2, 3, 4])

In [68]:
x[2:5] # by using positive slicing ccessing 2 to 4 from the array

array([2, 3, 4])

In [82]:
x[-3:]  # by using positive slicing ccessing 2 to 4 from the array

array([2, 3, 4])

# 2d array :

In [88]:
y = np.random.randint(0,20,(3,3)) # indexing on 2d array
y

array([[13, 17,  0],
       [15, 10,  2],
       [ 3, 10, 11]])

In [94]:
y[::2,::2] 

array([[13,  0],
       [ 3, 11]])

# 3d array :

In [112]:
z = np.random.randint(0,100,(3,3,3)) # indexing on 3d array
z

array([[[17,  1, 13],
        [78, 37, 19],
        [18, 79, 36]],

       [[45, 37, 20],
        [ 2, 69, 56],
        [33, 81, 58]],

       [[65, 41,  8],
        [23, 41, 54],
        [21, 19, 21]]])

In [115]:
z[::2,::2,::2]

array([[[17, 13],
        [18, 36]],

       [[65,  8],
        [21, 21]]])

# 4d array :

In [116]:
z = np.random.randint(0,100,(2,2,3,3)) # indexing on 4d array
z

array([[[[60, 83, 39],
         [49, 84, 75],
         [38, 13, 10]],

        [[45, 62,  9],
         [46,  9, 31],
         [35, 25, 74]]],


       [[[47, 23, 25],
         [38, 65, 10],
         [81, 47, 19]],

        [[95, 59, 21],
         [31, 47, 41],
         [74, 61, 42]]]])

In [124]:
z[:,:,::2,::2]

array([[[[60, 39],
         [38, 10]],

        [[45,  9],
         [35, 74]]],


       [[[47, 25],
         [81, 19]],

        [[95, 21],
         [74, 42]]]])

# Broadcasting
* If the arrays do not have the same rank (number of dimensions), prepend the shape of the smaller array with ones until both shapes have the same length.
* The sizes of the arrays must match in each dimension, or the size of one of the arrays must be 1.

In [154]:
x = np.arange(3) 
y = np.arange(9,18).reshape(3,3)
print(x+y)

[[ 9 11 13]
 [12 14 16]
 [15 17 19]]


# Axis:
Axis in NumPy refer to the directions along which operations like indexing, slicing, and reductions (e.g., sum, mean) are performed. In a multi-dimensional array, each dimension is associated with an axis. axis = 0 (rows), axis = 1(colums)

In [128]:
z = np.random.randint(0,100,(3,3)) #  3d array
z

array([[36, 14, 78],
       [57, 61, 39],
       [52, 63, 39]])

In [131]:
np.min(z, axis=0) # minimum values of each row from the given matrix

array([36, 14, 39])

In [132]:
np.min(z, axis=1) # minimum values of each colums from the given matrix

array([14, 39, 39])

# iterate
In NumPy, you can iterate over arrays in various ways to access and manipulate the elements


In [135]:
x = np.arange(0,5) # iterate on 1d array
x

array([0, 1, 2, 3, 4])

In [138]:
for i in x:
    print(i)

0
1
2
3
4


In [4]:
x = np.arange(9).reshape(3,3) # iterate on 2d array
x

2

In [143]:
for i in x:
    print(i)

[0 1 2]
[3 4 5]
[6 7 8]


In [144]:
for i in np.nditer(x):
    print(i)

0
1
2
3
4
5
6
7
8


# Stacking
Stacking involves combining multiple arrays into a single array along a specified axis.

# Vertical Stacking: np.vstack()
Stacks arrays in a row-wise manner (along the first axis).



In [166]:
x = np.arange(6).reshape(2,3)
y = np.arange(6,12).reshape(2,3)
print(x,y, sep=' \n\n')

[[0 1 2]
 [3 4 5]] 

[[ 6  7  8]
 [ 9 10 11]]


In [167]:
np.vstack((x,y))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

# Horizontal Stacking: np.hstack()
Stacks arrays in a column-wise manner (along the second axis).

In [169]:
x = np.arange(6).reshape(2,3)
y = np.arange(6,12).reshape(2,3)
print(x,y, sep=' \n\n')

[[0 1 2]
 [3 4 5]] 

[[ 6  7  8]
 [ 9 10 11]]


In [168]:
np.hstack((x,y))

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

# Splitting Arrays
Splitting divides a single array into multiple smaller arrays. There are several methods for splitting arrays.

# Basic Splitting: np.split()
Splits an array into multiple sub-arrays.

In [174]:
x = np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [177]:
np.split(x, 3)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

# Horizontal Split: np.hsplit()
Splits an array along the columns.

In [178]:
x = np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [179]:
np.hsplit(x,3) # it split the columns

[array([[0],
        [3],
        [6]]),
 array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]])]

# vertical Split: np.vsplit()
Splits an array along the rows.

In [180]:
x = np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [185]:
np.vsplit(x,3) # it split the rows

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]